spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    cache: false 
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

server:
  port: 8080
