spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_bd?characterEncoding=UTF-8
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    cache: false 
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

  web:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: 8080
